config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'users/index'
  devise_for :users, controllers: {    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'boards#index'
  resources :updatesnew, only:[:index]
  namespace :admin do
    resources :updates, only:[:new,:create]
  end
  resources :favorites, only:[:show, :create, :deresourcesstroy]
  resources :notifications, only:[:index]
  resources :boards, only:[:index,:new, :create,:edit,:update, :destroy] do
    resources :tasks do
      resources :comments, only:[:index,:new ,:create, :update, :destroy]
    end
  end

  resources :accounts, only: [:index,:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end

  resource :profile, only:[:edit, :update]
  resources :rooms, only:[:index, :show, :create]
  resources :messages, only:[:create]
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (board_id => boards.id)
#
class Task < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true

    belongs_to :user
    belongs_to :board
    has_many :comments, dependent: :destroy
    has_many :notofications, dependent: :destroy
    has_one_attached :eyecatch
    has_rich_text :description

    def comment_count
        comments.count
    end

    def archive_count
		archives.count
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!

    def index
      @board = Board.find(params[:board_id])
      @tasks = @board.tasks.page(params[:page]).per(4)
    end

    def show
      @board = Board.find(params[:board_id])
      @task = Task.find(params[:id])
    end

    def new
      @board = Board.find(params[:board_id])
      @task = @board.tasks.build
    end

    def create
      @board = Board.find(params[:board_id])
      @task = @board.tasks.build(task_params)

      if @task.save
        redirect_to board_tasks_path(@board)
      else
        render :new
      end
    end

    def edit
      @board = Board.find(params[:board_id])
      @task = current_user.tasks.find(params[:id])
    end

    def update
      @board = Board.find(params[:board_id])
      @task = current_user.tasks.find(params[:id])

      if @task.update(task_params)
        redirect_to board_task_path(@board,@task),notice: 'Completed Update'
      else
        flash.now[:error] = 'Failed Update'
        render :edit
      end
    end

    def destroy
      board = Board.find(params[:board_id])
      task = current_user.tasks.find(params[:id])
      task.destroy
      redirect_to board_path(board), notice:'Completed Destroy'
    end

    private
    def task_params
        params.require(:task).permit(:name,:description,:deadline,:eyecatch).merge(user_id: current_user.id)
    end
end

app/views/tasks/edit.html.haml
.container
  %ul
  - @task.errors.full_messages.each do |message|
    %li= message


  = form_with(model: @task, url: board_task_path(@board,@task), method: 'put', local: true, class: 'mb-5') do |f|
    %div
      = f.label :name,'Eyecatch'
    %di
      = f.file_field :eyecatch, class:'text'
    %div
      = f.label :name, 'Name'
    %div
      = f.text_field :name, class: 'text'
    %div
      = f.label :description, 'Description'
    %div
      = f.rich_text_area :description
    = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/index.html.haml
.container.mt-5
	=render 'commons/createboard'
	.row.container-board.mb-5
		.col-12.col-md-8
			%h2.text-info.text-center 募集内容
			= render 'commons/cardcontent',board:@board
			- if user_signed_in? && current_user.has_written?(@board)
				.row.board_detail_actions
					.col-6
						= link_to '編集', edit_board_path(@board),class:'btn btn-info w-100'
					.col-6
						= link_to '削除', board_path(@board), data: {method: 'delete', confirm: '本当に削除してもよろしいですか?', disabled_with:'処理中...'},class:'btn btn-danger w-100'
		.col-12.mt-4.col-md-4.mt-md-0
			%h2.text-info.text-center.mt-5.mt-md-0 募集している人
			.card
				.row.mb-3.justify-content-center
					= link_to account_path(@board.user) do
						= image_tag @board.user.avatar_image,class:'mr-0'
				.row.justify-content-center
					- if @board.user.profile.present?
						%p= @board.user.profile.nickname
					-else
						%p Noname
				.row
					.col-6.col-md-6
						%p.text-center.small フォロワー
						%p.text-center= @board.user.followers.count
					.col-6.col-md-6
						%p.text-center.small フォロー
						%p.text-center= @board.user.followings.count
					.col-12
						= link_to account_path(@board.user),class:'text-decoration-none text-white' do
							.btn.btn-info.w-100 プロフィールを確認
	.row
		.col-12
			-unless current_user == @board.user
				= link_to '提案を作成する', new_board_task_path(@board), class:'btn btn-first'
			%h2.text-info.text-center.mt-5 過去の提案一覧
			%p.text-center= "現在の提案数：#{@board.tasks.count}件"
	.row.mb-5
		-@tasks.limit(4).each do |task|
			.col-12.col-md-6
				.card#task-show{data:{board_id: @board.id, task_id: task.id}}
					=link_to board_task_path(@board,task) do
						- if task.eyecatch&.attached?
							= image_tag task.eyecatch, class:'task_eyecatch mb-5'
						- else
							= image_tag 'background-default.png',class:'task_eyecatch mb-5'
					.card_name.d-flex
						= task.name
					.card_description
						= task.description
					.card_detail.d-flex
						= image_tag task.user.avatar_image
		.col-12
			= link_to board_tasks_path do
				.btn.btn-first.text-white 提案一覧を見る
	=render 'commons/scrollup'
	=paginate @tasks
	=javascript_pack_tag 'board'
	=javascript_pack_tag 'task'

app/views/tasks/new.html.haml
.container
  %ul
  - @task.errors.full_messages.each do |message|
    %li= message
  = form_with(model: @task, url: board_tasks_path, method: 'post', local: true, class: 'mb-5') do |f|
    %div
      = f.label :eyecatch,'アイキャッチ画像'
    %div
      = f.file_field :eyecatch,class:'text'
    %div
      = f.label :name, 'タイトル'
    %div
      = f.text_field :name, class: 'text'
    %div
      = f.label :description, 'メッセージ内容'
    %div
      = f.rich_text_area :description
    = f.submit '提案する',data:{confirm:'提案を完了しても良いですか？',disable_with:'処理中...'} ,class: 'btn-first'

app/views/tasks/show.html.haml
.container.mt-5
  =render 'commons/createboard'
  =link_to '前のページに戻る',:back,class:'btn btn-info'
  .task#task-show{data:{user_id: current_user.id, user_nickname: current_user.profile.nickname, board_id: @board.id, task_id: @task.id}}
    .task_title
      %h2.task_name= @task.name
      - if user_signed_in? && current_user.has_written_task?(@board,@task)
        .board_detail.actions
          .dropdown
            = image_tag 'actions.svg',class:'dropbtn'
            .dropdown-content.mini
              = link_to '編集', edit_board_task_path(@board,@task)
              = link_to '削除', board_task_path(@board,@task), data:{method:'delete',confirm:'本当に削除してよろしいですか？'}
    - if @task.eyecatch&.attached?
      = image_tag @task.eyecatch, class:'task_eyecatch'
    - else
      = image_tag 'background-default.png',class:'task_eyecatch'
    .card
      .card_content
        .card_description
          = @task.description
  %h2.task_comment コメント一覧
  .comment-container

  .new_board.mb-5
    .btn.btn-first.show-comment-form
      %p.mb-0 コメント追加
    .comment-text-area.hidden
      =text_area_tag :comment_content, '', class:'sm'
    .btn.btn-first.add-comment-button.hidden
      %p.mb-0 コメント追加

=javascript_pack_tag 'task'
=javascript_pack_tag 'board'