config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'users/index'
  devise_for :users, controllers: {    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'boards#index'
  resources :updatesnew, only:[:index]
  namespace :admin do
    resources :updates, only:[:new,:create]
  end
  resources :favorites, only:[:show, :create, :deresourcesstroy]
  resources :notifications, only:[:index]
  resources :boards, only:[:index,:new, :create,:edit,:update, :destroy] do
    resources :tasks do
      resources :comments, only:[:index,:new ,:create, :update, :destroy]
    end
  end

  resources :accounts, only: [:index,:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end

  resource :profile, only:[:edit, :update]
  resources :rooms, only:[:index, :show, :create]
  resources :messages, only:[:create]
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id         :bigint           not null, primary key
#  action     :string           default(""), not null
#  checked    :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :integer
#  comment_id :integer
#  task_id    :integer
#  visited_id :integer
#  visitor_id :integer
#
# Indexes
#
#  index_notifications_on_board_id    (board_id)
#  index_notifications_on_comment_id  (comment_id)
#  index_notifications_on_task_id     (task_id)
#  index_notifications_on_visited_id  (visited_id)
#  index_notifications_on_visitor_id  (visitor_id)
#
class Notification < ApplicationRecord
	default_scope -> { order(created_at: :desc) }
	belongs_to :board, optional: true
  belongs_to :task, optional: true
  belongs_to :comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
	end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.haml
.row.align-items-center.justify-content-center
	- visitor = notification.visitor
	- visited = notification.visited
	- unless visitor.blank?
		= image_tag visitor.avatar_image, class: "header_avatar mr-1"
		%strong
			-if visitor.email == 'guest@gmail.com'
				%p ゲストユーザー
			-else
				= link_to account_path(visitor) ,class:'text-warning' do
					= visitor.profile.nickname
		= 'さんが'
		- case notification.action
		- when 'follow' then
			= "あなたをフォローしました"
			%p.mb-0.ml-4= "#{time_ago_in_words(notification.created_at)}前"
		- when 'like' then
			%strong
				= link_to 'あなたの投稿', board_tasks_path(notification.board), class:'text-warning'
			= 'にいいねしました'
			%p.mb-0.ml-4= "#{time_ago_in_words(notification.created_at)}前"
	- else
		%p.mb-0 通知はありません
%hr

app/views/notifications/index.html.haml
/ 自分の投稿に対するいいね、コメントは通知に表示しない
.container.mt-5
	%h2.text-info 通知一覧
	- notifications = @notifications.where.not(visitor_id: current_user.id)
	- if notifications.exists?
		%hr
		= render notifications
		= paginate notifications
	- else
		%p 通知はありません