config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'users/index'
  devise_for :users, controllers: {    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'boards#index'
  resources :updatesnew, only:[:index]
  namespace :admin do
    resources :updates, only:[:new,:create]
  end
  resources :favorites, only:[:show, :create, :deresourcesstroy]
  resources :notifications, only:[:index]
  resources :boards, only:[:index,:new, :create,:edit,:update, :destroy] do
    resources :tasks do
      resources :comments, only:[:index,:new ,:create, :update, :destroy]
    end
  end

  resources :accounts, only: [:index,:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end

  resource :profile, only:[:edit, :update]
  resources :rooms, only:[:index, :show, :create]
  resources :messages, only:[:create]
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action:authenticate_user!
  def index
    @user = User.all
  end

	def show
		@user = User.find(params[:id])
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id = u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end

      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
	end
end

app/views/accounts/show.html.haml
.container.mb-5.pb-5
	%h2.mt-3.text-info プロフィール
	.profile.mt-3.bg-white.p-3
		.profile_info
		= image_tag @user.avatar_image,class:'header_avatar'
		-if @user.profile.present?
			%h3.mt-2.font-weight-bold= @user.profile.nickname
			%p.mt-2= @user.profile.introduction
		-else
			%h3.mt-2.font-weight-bold ニックネームが未設定
			%p.mt-2 自己紹介が未設定
		- if @user == current_user
			= link_to 'プロフィールを編集',edit_profile_path, class:'btn btn-info m-0 w-100'
		-else
			-if current_user&.has_followed?(@user)
				= link_to account_unfollows_path(@user),data:{method: 'post'},class:'ml-5 btn-user-unfollow btn btn-info' do
					%p.mb-0.user-follow-button.mb-0 フォロー解除
			-else
				= link_to account_follows_path(@user),data:{method: 'post'},class:'ml-5 btn-user-follow btn btn-info' do
					%p.mb-0.user-follow-button.mb-0 フォロー
	%hr
	%h2.py-3.text-info ユーザー
	-if @user.profile.present?
		-if @user.has_followed?(current_user)
			- unless @user.id == current_user.id
				- if @isRoom == true
					%p
						= link_to 'チャットへ', room_path(@roomId)
				- else
					= form_for @room do |f|
						= fields_for @entry do |e|
							= e.hidden_field :user_id, :value=> @user.id
						= f.submit "チャットを始める",class:'btn-first'
		- else
			%p.text-info ＊相互フォローの場合のみ、メッセージを送信できます。
	= link_to "ユーザー一覧に戻る", users_index_path
	%hr
	.container-board
		%h2.mt-3.text-info 募集一覧
		.row.mx-auto.card_row
			- if @user.boards.present?
				- @user.boards.each do |board|
					.card.col-12.mx-auto
						.card_content
							.card_name
								= board.name
							.card_description
								= board.content
							.card_taglist
								=render 'commons/tag_list',tag_list: board.tag_list
			- else
				%p まだ募集がありません